### ISSUE TITLE
possible funding opportunities

### ISSUE THREAD

**Issue by troettge** [troettge/RN-Norway#4]
Add and comment with further information

1. [ReNEW](https://www.uio.no/english/research/strategic-research-areas/nordic/news-and-events/announcements/2021/renew-call-spring2021.html)
2. [UiO Norden](https://www.uio.no/english/research/strategic-research-areas/nordic/news-and-events/announcements/open-call/Open%20call%20uio%20nordic.html)
3. [UiO Life Sciences](https://www.uio.no/forskning/satsinger/livsvitenskap/aktuelt/finansiering/2021/sok-arrangementsstotte_12.html)
4. [Fritt Ord](https://frittord.no/en/home)

**Comment by julienmayor** [comment]
5. Should we make enquiries if UiO/faculties/departments are willing to provide support? 
RN is supra-universities, but given that all "founding members" are affiliated at UiO, we can argue this gives visibility to UiO.

**Comment by troettge** [comment]
- [ ]  set up gdocs
- [ ]  invite everybody
- [ ]  compile options with requirements etc.

@ Siri

**Comment by agboch** [comment]
@dsquintana @troettge @julienmayor I forgot to mention it at the meeting and it might be a long shot but EU has several funding programs now for open science/research reproducibility that we should check out (deadline in April):
1.	[HORIZON-WIDERA-2022-ERA-01-40: Stepping-up institutional and territorial changes towards open and responsible research and innovation](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/horizon-widera-2022-era-01-40;callCode=null;freeTextSearchKeyword=HORIZON-WIDERA-2022-ERA-01-40;matchWholeText=true;typeCodes=1,2;statusCodes=31094501;programmePeriod=null;programCcm2Id=null;programDivisionCode=null;focusAreaCode=null;destination=null;mission=null;geographicalZonesCode=null;programmeDivisionProspect=null;startDateLte=null;startDateGte=null;crossCuttingPriorityCode=null;cpvCode=null;performanceOfDelivery=null;sortQuery=sortStatus;orderBy=asc;onlyTenders=false;topicListKey=topicSearchTablePageState)
2.	[HORIZON-WIDERA-2022-ERA-01-41: Increasing the reproducibility of scientific results](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/horizon-widera-2022-era-01-41;callCode=null;freeTextSearchKeyword=HORIZON-WIDERA-2022-ERA-01-41;matchWholeText=true;typeCodes=1,2;statusCodes=31094501;programmePeriod=null;programCcm2Id=null;programDivisionCode=null;focusAreaCode=null;destination=null;mission=null;geographicalZonesCode=null;programmeDivisionProspect=null;startDateLte=null;startDateGte=null;crossCuttingPriorityCode=null;cpvCode=null;performanceOfDelivery=null;sortQuery=sortStatus;orderBy=asc;onlyTenders=false;topicListKey=topicSearchTablePageState)
3.	[HORIZON-WIDERA-2022-ERA-01-42: Supporting the development of aligned policies for open access books and monographs](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/horizon-widera-2022-era-01-42;callCode=null;freeTextSearchKeyword=HORIZON-WIDERA-2022-ERA-01-42;matchWholeText=true;typeCodes=1,2;statusCodes=31094501;programmePeriod=null;programCcm2Id=null;programDivisionCode=null;focusAreaCode=null;destination=null;mission=null;geographicalZonesCode=null;programmeDivisionProspect=null;startDateLte=null;startDateGte=null;crossCuttingPriorityCode=null;cpvCode=null;performanceOfDelivery=null;sortQuery=sortStatus;orderBy=asc;onlyTenders=false;topicListKey=topicSearchTablePageState)
4.	[HORIZON-WIDERA-2022-ERA-01-44: Developing and piloting training on the practice of open and responsible research and innovation](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search;callCode=null;freeTextSearchKeyword=HORIZON-WIDERA-2022-ERA-01-44;matchWholeText=true;typeCodes=1,2;statusCodes=31094501;programmePeriod=null;programCcm2Id=null;programDivisionCode=null;focusAreaCode=null;destination=null;mission=null;geographicalZonesCode=null;programmeDivisionProspect=null;startDateLte=null;startDateGte=null;crossCuttingPriorityCode=null;cpvCode=null;performanceOfDelivery=null;sortQuery=sortStatus;orderBy=asc;onlyTenders=false;topicListKey=topicSearchTablePageState)
 
I only worry that since the network is locally in Norway then it might not be as relevant for these calls and it would make more sense to apply for national funds (unless we pair up with other RNs and apply together?).

**Comment by sirileknes** [comment]
I talked to the department about giving us an administrative resource for 2022, just followed up on email with Dan and Julien on cc. I'm hopeful they'll pull through on this.

**Comment by troettge** [comment]
Great that you reached out to your chair. Would you mind forwarding the email exchange to us (Agata and me)? I think we should discuss what an admin at this stage would do in the first place. I am also worried that if getting an admin admin, they will not be qualified for most tasks at hand (help organize events, website maintenance, communication). Would be great to have someone with experience in both research and open science and particular skill sets to fill such a role. What do others think?

**Comment by agboch** [comment]
Thanks for the initiative, Siri. I agree that we should have probably talked about what we would use such administrative resource for and what would be the best solution for that before we reach out to anybody. We work here as a team and we try to coordinate all the decisions and all the steps together, both here on Github and at the meetings, so let's try to keep everybody in the loop about all ideas that come up (and copy the whole team on any emails about the network).

**Comment by sirileknes** [comment]
As I recall, we discussed the need for an administrative resource in our initial talks. It was the clear message from the other national societies that administrative support is key to get things rolling. It's hard to understand how it could possibly be controversial if my initiative brings in some funding. 
Also, I assume working in a team does not include micromanaging each other? I will try not to read your comments in that spirit. 
If we do get this funding, we will undoubtedly have tasks for the admin to do, and there would be plenty of time for us to figure out exactly what. I cc'd Julien and Dan on the email because it's strategically useful to show the department chair that the initiative includes staff from three sections. I hope this clarifies things and alleviates your concerns.

**Comment by troettge** [comment]
I understand that you are keen to take action and I admire your drive. However, your response does not alleviate the concern for me. Agata's concern has nothing to do with micromanaging, it has to do with transparency, collective decision making, and a healthy communication culture. You just went ahead and took action without even discussing it with us. Moreover, the actual conversation remains intransparent to 2 out of 5 members. I would like to reiterate that if we want to move forward together, I would like us to be much more explicit and transparent about developments that concern the group’s efforts.
 
With regard to the admin question: In our last meeting, we discussed the next steps for 2022 and we agreed that these are mainly involving contacting people and organising two educational events. I think its admirable how much thirst for action you have and I consider it a great fortune to have you with us, but for a functional team, I consider communication the key. That does also include, and I will mention it now, letting us know if you cannot make it to a meeting in advance.
